name: Compile and upload CV PDF
on:
    push:
        branches:
            - "main"
        paths:
            - "cv.tex"
            - "index.html"
            - ".github/workflows/**"

jobs:
    build_latex:
        runs-on: ubuntu-latest
        container:
            image: danteev/texlive:latest
        steps:
            - name: Change Owner of Container Working Directory
              run: chown root:root .

            - name: Checkout
              uses: actions/checkout@v4
              with:
                  persist-credentials: false

            # - name: build document class
            #   run : | 
            #       apt-get install texlive-xetex
            #       xelatex limecv.ins

            - name: Compile LaTeX document
              uses: xu-cheng/latex-action@v3
              with:
                  root_file: cv.tex

            - name: Post Processing
              run: |
                  mkdir build 
                  cp *.pdf build/ 
                  cp index.html build/
                  
            - name: Git add
              run: git add build/
              
            - name: Deploy to GitHub Pages branch
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                  BRANCH: gh-pages
                  FOLDER: build
                  TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  CLEAN: true