name: Compile latex 
on:
  push:
    branches:
      - "main"
    paths:
      - "cv.tex"
      - "index.html"
      - ".github/workflows/**"
      

jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:latest
    steps:
      - name: Change Owner of Container Working Directory
        run: chown root:root .

      - name: Install fontawesome5 package
        run: |
          apt-get update && apt-get install -y --no-install-recommends \
            texlive-fonts-extra

      - name: Checkout
        uses: actions/checkout@v4
        with:
            persist-credentials: false

      - name: Install Fira Fonts
        run: |
          mkdir -p ~/.fonts
          cp fonts/* ~/.fonts
          fc-cache -fv                  

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
            root_file: cv.tex
            latexmk_use_xelatex: true

      - name: Post Processing
        run: |
            mkdir build 
            cp *.pdf build/ 
            cp index.html build/
            
      - name: Git add
        run: git add build/
        
      - name: Deploy to GitHub Pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          FOLDER: build
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
          CLEAN: true